# TTS Config: https://github.com/kyutai-labs/moshi/blob/main/rust/moshi-server/tts.py#L53
static_dir = "./static/"
log_dir = "/tmp/unmute_logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts-streaming"
text_tokenizer_file = "hf://kyutai/tts-1.6b-en_fr/tokenizer_spm_8k_en_fr_audio.model"
batch_size = 1  # NOTE: make this larger if multiple users / gpu vram
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/tmp/unmute_logs"
# We could use replace **/*.safetensors with unmute-prod-website/*.safetensors
# to only get the voices used in Unmute, but we are using the TTS for the demo
# on the project page too and for that we want to load the other voices as well
voice_folder = "hf-snapshot://kyutai/tts-voices/**/*.safetensors"
default_voice = "unmute-prod-website/ex04_narration_longform_00001.wav"
cfg_coef = 2.0
cfg_is_no_text = true
padding_between = 1
n_q = 24

# STT Config: https://github.com/kyutai-labs/moshi/blob/main/rust/moshi-server/voice.py#L546
# [modules.asr]
# path = "/api/stt-streaming"
# type = "BatchedAsr"
# lm_model_file = "hf://kyutai/stt-1b-en_fr-candle/model.safetensors"
# text_tokenizer_file = "hf://kyutai/stt-1b-en_fr-candle/tokenizer_en_fr_audio_8000.model"
# audio_tokenizer_file = "hf://kyutai/stt-1b-en_fr-candle/mimi-pytorch-e351c8d8@125.safetensors"
# asr_delay_in_tokens = 6
# batch_size = 1  # NOTE: make this larger if multiple users / gpu vram
# conditioning_learnt_padding = true
# temperature = 0.25

# [modules.asr.model]
# audio_vocab_size = 2049
# text_in_vocab_size = 8001
# text_out_vocab_size = 8000
# audio_codebooks = 20

# [modules.asr.model.transformer]
# d_model = 2048
# num_heads = 16
# num_layers = 16
# dim_feedforward = 8192
# causal = true
# norm_first = true
# bias_ff = false
# bias_attn = false
# context = 750
# max_period = 100000
# use_conv_block = false
# use_conv_bias = true
# gating = "silu"
# norm = "RmsNorm"
# positional_embedding = "Rope"
# conv_layout = false
# conv_kernel_size = 3
# kv_repeat = 1
# max_seq_len = 40960

# [modules.asr.model.extra_heads]
# num_heads = 4
# dim = 6